### ISSUE TITLE
test regresion in 3.2.1 async gevent

### ISSUE THREAD

**Issue by anthraxx** [miguelgrinberg/python-engineio#89]
I somehow can't make the teset suite pass anymore, failing with the following error:

I have also tried backporting bc128c2e3f41a69d855acabdbdbad072f662df92 but it didn't change the result.

python 3.7
gevent 1.3.7
gevent-websocket 0.10.1
websocket-client 0.54.0
python-urllib3 1.24.1
eventlet 0.24.1

```python
======================================================================
FAIL: test_async_mode_gevent (tests.common.test_server.TestServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/mock.py", line 1195, in patched
    return func(*args, **keywargs)
  File "/build/python-engineio/src/python-engineio-3.2.1/tests/common/test_server.py", line 193, in test_async_mode_gevent
    self.assertEqual(s._async['queue'], 'foo')
AssertionError: <class 'gevent._queue.JoinableQueue'> != 'foo'

======================================================================
FAIL: test_async_mode_gevent_without_websocket (tests.common.test_server.TestServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/mock.py", line 1195, in patched
    return func(*args, **keywargs)
  File "/build/python-engineio/src/python-engineio-3.2.1/tests/common/test_server.py", line 216, in test_async_mode_gevent_without_websocket
    self.assertEqual(s._async['queue'], 'foo')
AssertionError: <class 'gevent._queue.JoinableQueue'> != 'foo'

----------------------------------------------------------------------
Ran 408 tests in 2.832s

FAILED (failures=2)
Test failed: <unittest.runner.TextTestResult run=408 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=408 errors=0 failures=2>
```

some help would be appreciated

**Comment by miguelgrinberg** [comment]
Fix in progress. In the meantime please downgrade this package to version 3.2.0.

**Comment by miguelgrinberg** [comment]
Fixed. Please upgrade python-engineio to 3.2.2. Sorry for the mistake.

**Comment by anthraxx** [comment]
thanks a lot, always a pleasure how fast you fix things and care about your projects :heart:

**Comment by anthraxx** [comment]
@miguelgrinberg hm im using 3.2.2 now but still the same test error

**Comment by miguelgrinberg** [comment]
The tests are passing in the build. The JoinableQueue should be mocked in those tests.

**Comment by anthraxx** [comment]
i have seen travis, but that still doesn't pass here. I have no idea why, all deps are latest versions.

**Comment by anthraxx** [comment]
@miguelgrinberg there are no tests yet for python 3.7 i can imagine the import mocking maybe works differently? Until this passes I can't release engineio for Arch Linux repos :(

**Comment by miguelgrinberg** [comment]
I run the tests locally under 3.7, they pass for me:

```
----------------------------------------------------------------------
Ran 408 tests in 2.719s

OK
sys:1: RuntimeWarning: coroutine 'AsyncMock.<locals>.mock_coro' was never awaited
py37 runtests: commands[1] | coverage report --show-missing
Name                                     Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------------
engineio/__init__.py                         6      0      0      0   100%
engineio/async_drivers/__init__.py           0      0      0      0   100%
engineio/async_drivers/aiohttp.py           34      0      8      0   100%
engineio/async_drivers/asgi.py              68      0     32      0   100%
engineio/async_drivers/eventlet.py          15      0      2      0   100%
engineio/async_drivers/gevent.py            10      0      0      0   100%
engineio/async_drivers/gevent_uwsgi.py       8      0      0      0   100%
engineio/async_drivers/threading.py          6      0      0      0   100%
engineio/async_drivers/tornado.py           47      0     10      0   100%
engineio/asyncio_client.py                 289      0    100      0   100%
engineio/asyncio_server.py                 173      0     64      0   100%
engineio/asyncio_socket.py                 144      0     48      0   100%
engineio/client.py                         343      0    112      0   100%
engineio/exceptions.py                      12      0      0      0   100%
engineio/middleware.py                      28      0      8      0   100%
engineio/packet.py                          68      0     40      0   100%
engineio/payload.py                         41      0     18      0   100%
engineio/server.py                         268      0     96      0   100%
engineio/socket.py                         157      0     48      0   100%
------------------------------------------------------------------------------------
TOTAL                                     1717      0    586      0   100%
py37 runtests: commands[2] | coverage erase
_____________________________________________________ summary _____________________________________________________  py37: commands succeeded
  congratulations :)
```

So what's different on your side? I'm using 3.7.1 here, and start the tests with `tox -epy37`. How are you doing it?

**Comment by anthraxx** [comment]
I'm bit lost why it breaks for gevent_* tests but works for gevent_uwsgi_* tests

**Comment by felixonmars** [comment]
The cause is likely test_async_modes_wsgi in test_asyncio_server.py imported that driver (when trying async_mode), which is prior to the mock in test_server. The gevent_uwsgi part wasn't affected because running the tests outside of uwsgi fails on "import uwsgi", so the driver wasn't imported successfully without mock.

**Comment by miguelgrinberg** [comment]
Fixed in 3.2.3. Thanks!
